[package]
name = "kvs"
version = "0.1.0"
authors = ["poppindouble <poppindouble@gmail.com>"]
description = "Simple string kv engine."
edition = "2018"

[dependencies]
clap = "2.33.0"

[dev-dependencies]
assert_cmd = "0.11.0"